# Generated by Django 4.0.3 on 2022-06-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing_bid_listing_bid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
