# Generated by Django 4.0.3 on 2022-06-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_current_bid_listing_starting_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.listing'),
        ),
    ]
