# Generated by Django 4.0.3 on 2022-06-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_user_bids_user_bids_remove_user_listings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bids',
        ),
        migrations.AddField(
            model_name='user',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='user_bids', to='auctions.bid'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='listings',
        ),
        migrations.AddField(
            model_name='user',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='user_listings', to='auctions.listing'),
        ),
    ]
