# Generated by Django 4.0.3 on 2022-06-17 13:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_user_bids_user_bids_remove_user_listings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='user',
            name='listings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.AddField(
            model_name='listing',
            name='mod_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='listing',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
