# Generated by Django 4.0.3 on 2022-06-21 17:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='bidders',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='mod_date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bid', to='auctions.bid'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bidders',
            field=models.ManyToManyField(blank=True, related_name='buyers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='mod_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='listing',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
