# Generated by Django 4.0.3 on 2022-06-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_entry_bid_remove_entry_bidders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.ManyToManyField(null=True, related_name='current_bid', to='auctions.bid'),
        ),
    ]
