# Generated by Django 4.0.3 on 2022-06-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_remove_listing_comments_listing_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='comments',
        ),
        migrations.AddField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='listing_comments', to='auctions.comment'),
        ),
    ]
