# Generated by Django 4.0.3 on 2022-06-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(null=True, related_name='listing_category', to='auctions.category'),
        ),
    ]
