# Generated by Django 4.0.3 on 2022-06-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='listing_comments', to='auctions.comment'),
        ),
    ]
