# Generated by Django 4.1.2 on 2022-11-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_alter_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/listings_pics'),
        ),
    ]
