# Generated by Django 4.1.2 on 2022-11-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_listing_listing_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
